server:
  port: 8888
  
spring:
  application:
    name: CONFIG-SERVER
    
  
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Navya9972/Microservices-Hotel
          clone-on-start: true
